### PR TITLE
Adjust OpenStreetMap API URL

### PR DESCRIPTION
**Pull request by sqlstatement**
This pull request changes the URL used to get data from OpenStreetMap, as they have changed the format, which has effectively broken the entire wallpaper.

### CODE REVIEW

**Comment by sqlstatement** [comment]
Closing because there has been more than 1 month of inactivity.

**Comment by seanlennaerts** [comment]
@sqlstatement sorry only just now seeing this. Thank you for the contribution. I don't have time to test it now but if this is still valid please reopen it and I will merge it 👍

**Comment by sqlstatement** [comment]
@seanlennaerts PR reopened, I tested it locally to confirm it works and resolved the issue.

**Comment by seanlennaerts** [comment]
Thanks @sqlstatement! Didn't have time to test it myself but I'm sure it's good 👍

**Pull request merged**
